# Generated by Django 4.1.7 on 2023-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accesslevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('access', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminEmail', models.CharField(max_length=15)),
                ('adminPassword', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='assignedvaccine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('HCW_Name', models.CharField(max_length=25)),
                ('Vaccine_Type', models.CharField(max_length=25)),
                ('Vaccine_Quantity', models.IntegerField()),
                ('Vaccine_Name', models.CharField(max_length=25)),
                ('directorEPI_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('Father_Email', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=500)),
                ('Contact', models.IntegerField()),
                ('Father_CNIC', models.IntegerField()),
                ('Mother_CNIC', models.IntegerField()),
                ('Hospital_Name', models.CharField(max_length=500)),
                ('Hospital_ID', models.IntegerField()),
                ('HCW_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='directorEPI',
            fields=[
                ('directorEPIFirstname', models.CharField(max_length=25)),
                ('directorEPILastname', models.CharField(max_length=25)),
                ('directorEPIEmail', models.CharField(max_length=15)),
                ('directorEPIPassword', models.CharField(max_length=15)),
                ('directorEPIProvince', models.CharField(max_length=25)),
                ('directorEPIphone', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackID', models.IntegerField()),
                ('msg', models.CharField(max_length=100)),
                ('userID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='healthcareworker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=15)),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('Contact', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('directorEPI_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hospitalName', models.CharField(max_length=25)),
                ('hospitalStatus', models.CharField(max_length=15)),
                ('hospitalCity', models.CharField(max_length=25)),
                ('hospitalProvince', models.CharField(max_length=25)),
                ('hospitalAddress', models.CharField(max_length=25)),
                ('adminId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='medicalSuperIntendent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('medicalSuperIntendentEmail', models.CharField(max_length=15)),
                ('medicalSuperIntendentPassword', models.CharField(max_length=15)),
                ('medicalSuperIntendentFirstname', models.CharField(max_length=25)),
                ('medicalSuperIntendentLastname', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('hospitalID', models.IntegerField()),
                ('hospitalName', models.CharField(max_length=25)),
                ('adminId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenID', models.IntegerField()),
                ('userID', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='vaccine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vaccineName', models.CharField(max_length=15)),
                ('vaccinetype', models.CharField(max_length=15)),
                ('vaccinequantity', models.CharField(max_length=15)),
                ('vaccinedescription', models.CharField(max_length=15)),
                ('adminId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vaccineRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('Father_CNIC', models.IntegerField()),
                ('Mother_CNIC', models.IntegerField()),
                ('Vaccine_ID', models.IntegerField()),
                ('Vaccine_Name', models.CharField(max_length=15)),
                ('Vaccine_Type', models.CharField(max_length=15)),
                ('Vaccine_Description', models.CharField(max_length=15)),
                ('HCW_ID', models.IntegerField()),
            ],
        ),
    ]
