# Generated by Django 4.1.7 on 2023-02-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcareworker',
            name='phone',
        ),
    ]
